# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch

random_tensor = torch.rand(3, 3)

print(random_tensor)



### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
import torch

tensor1 = torch.rand(3, 3)

tensor2 = torch.rand(3, 3)

result = torch.mm(tensor1, tensor2)

print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)
print("\nMatrix Multiplication Result:\n", result)


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
import torch

torch.manual_seed(42)

tensor1 = torch.rand(3, 3)

tensor2 = torch.rand(3, 3)

result = torch.mm(tensor1, tensor2)


print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)
print("\nMatrix Multiplication Result:\n", result)


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:

import torch


torch.manual_seed(42)


if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)  

print("Random seed set for both CPU and GPU ✅")



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

torch.manual_seed(42)
torch.cuda.manual_seed(42)


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

tensor1 = torch.rand(3, 3, device=device)
tensor2 = torch.rand(3, 3, device=device)


result = torch.mm(tensor1, tensor2)


print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)
print("\nMatrix Multiplication Result:\n", result)
device = "cuda" if torch.cuda.is_available() else "cpu"



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
import torch

torch.manual_seed(42)
torch.cuda.manual_seed(42)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

tensor_A = torch.rand(3, 3, device=device)
tensor_B = torch.rand(3, 3, device=device)

result = torch.matmul(tensor_A, tensor_B)

print("Tensor A:\n", tensor_A)
print("\nTensor B:\n", tensor_B)
print("\nMatrix Multiplication Result:\n", result)



### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
import torch

torch.manual_seed(42)
result = torch.rand(3, 3)

max_value = torch.max(result)

min_value = torch.min(result)

print("Tensor:\n", result)
print("\nMaximum value:", max_value.item())
print("Minimum value:", min_value.item())


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
import torch

torch.manual_seed(42)
tensor = torch.rand(3, 3)

max_value = torch.max(tensor)
min_value = torch.min(tensor)

arg_max = torch.argmax(tensor)
arg_min = torch.argmin(tensor)

print("Tensor:\n", tensor)
print("\nMaximum value:", max_value.item(), "at index:", arg_max.item())
print("Minimum value:", min_value.item(), "at index:", arg_min.item())



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch

torch.manual_seed(42)

tensor = torch.rand(1, 3, 1, 3)

squeezed_tensor = torch.squeeze(tensor)

print("Original Tensor:\n", tensor)
print("Original Shape:", tensor.shape)

print("\nSqueezed Tensor:\n", squeezed_tensor)
print("Squeezed Shape:", squeezed_tensor.shape)
